import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["HACHIMICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["HACHIMICODE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("HACHIMICODE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  HACHIMICODE_AUTO_HEAP_SNAPSHOT: truthy("HACHIMICODE_AUTO_HEAP_SNAPSHOT"),
  HACHIMICODE_GIT_BASH_PATH: process.env["HACHIMICODE_GIT_BASH_PATH"],
  HACHIMICODE_CONFIG: process.env["HACHIMICODE_CONFIG"],
  HACHIMICODE_CONFIG_CONTENT: process.env["HACHIMICODE_CONFIG_CONTENT"],
  HACHIMICODE_DISABLE_AUTOUPDATE: truthy("HACHIMICODE_DISABLE_AUTOUPDATE"),
  HACHIMICODE_ALWAYS_NOTIFY_UPDATE: truthy("HACHIMICODE_ALWAYS_NOTIFY_UPDATE"),
  HACHIMICODE_DISABLE_PRUNE: truthy("HACHIMICODE_DISABLE_PRUNE"),
  HACHIMICODE_DISABLE_TERMINAL_TITLE: truthy("HACHIMICODE_DISABLE_TERMINAL_TITLE"),
  HACHIMICODE_SHOW_TTFD: truthy("HACHIMICODE_SHOW_TTFD"),
  HACHIMICODE_DISABLE_AUTOCOMPACT: truthy("HACHIMICODE_DISABLE_AUTOCOMPACT"),
  HACHIMICODE_DISABLE_MODELS_FETCH: truthy("HACHIMICODE_DISABLE_MODELS_FETCH"),
  HACHIMICODE_DISABLE_MOUSE: truthy("HACHIMICODE_DISABLE_MOUSE"),
  HACHIMICODE_FAKE_VCS: process.env["HACHIMICODE_FAKE_VCS"],
  HACHIMICODE_SERVER_PASSWORD: process.env["HACHIMICODE_SERVER_PASSWORD"],
  HACHIMICODE_SERVER_USERNAME: process.env["HACHIMICODE_SERVER_USERNAME"],
  HACHIMICODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("HACHIMICODE_DISABLE_FFF"),

  // Experimental
  HACHIMICODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("HACHIMICODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  HACHIMICODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("HACHIMICODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  HACHIMICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("HACHIMICODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  HACHIMICODE_MODELS_URL: process.env["HACHIMICODE_MODELS_URL"],
  HACHIMICODE_MODELS_PATH: process.env["HACHIMICODE_MODELS_PATH"],
  HACHIMICODE_DB: process.env["HACHIMICODE_DB"],

  HACHIMICODE_WORKSPACE_ID: process.env["HACHIMICODE_WORKSPACE_ID"],
  HACHIMICODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("HACHIMICODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get HACHIMICODE_DISABLE_PROJECT_CONFIG() {
    return truthy("HACHIMICODE_DISABLE_PROJECT_CONFIG")
  },
  get HACHIMICODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("HACHIMICODE_EXPERIMENTAL_REFERENCES")
  },
  get HACHIMICODE_TUI_CONFIG() {
    return process.env["HACHIMICODE_TUI_CONFIG"]
  },
  get HACHIMICODE_CONFIG_DIR() {
    return process.env["HACHIMICODE_CONFIG_DIR"]
  },
  get HACHIMICODE_PURE() {
    return truthy("HACHIMICODE_PURE")
  },
  get HACHIMICODE_PERMISSION() {
    return process.env["HACHIMICODE_PERMISSION"]
  },
  get HACHIMICODE_PLUGIN_META_FILE() {
    return process.env["HACHIMICODE_PLUGIN_META_FILE"]
  },
  get HACHIMICODE_CLIENT() {
    return process.env["HACHIMICODE_CLIENT"] ?? "cli"
  },
}
